trigger:
  batch: true
  branches:
    include:
    # for new release to production: release flow strategy
    - release/*
    - master
  
  
# Build 


# to Dev stage


# to Staging


# to Production